### ISSUE TITLE
Login with private key

### ISSUE THREAD

**Issue by macfarlanechristal** [suidouble/suidouble8192#1]
Yo bro can u make using accounts with Private key instead of seed phrase. I have 20 wallets on the same seedphrase which i need to use, but even if i put another public key in "youAre" its always using only first wallet on seedphrase. 

Also will be great if u can do multiple wallets running at the same time

**Comment by macfarlanechristal** [comment]
And also its just stucking after some time and need to restart, without any error

**Comment by jeka-kiselyov** [comment]
Sorry, but this is just a simple demo app for a suidouble library. I am not going to add any features to it. Feel free to fork and adjust though.
