### ISSUE TITLE
There are no points.

### ISSUE THREAD

**Issue by JerryX-collab** [suidouble/suidouble8192#2]
Sir, thanks for the code, it ran all night yesterday, I have two more questions for you, I recorded my score and rankings before I started, but after running all night my score did not increase, what is the reason for this and has it been officially banned? Also, could you please tell me how to set up multiple wallets to run at the same time, thank you very much!

**Comment by JerryX-collab** [comment]
May I ask if this loophole is officially banned, I can see the transaction history on the block, but my points won't get more

**Comment by jeka-kiselyov** [comment]
@ariel841005 they just may changed contract address to different one to support nft checking etc. As I am not participating in the challenge, don't have much time to debug it (and as this is just a demo app for a library), but feel free to.
