### ISSUE TITLE
About RPC

### ISSUE THREAD

**Issue by JerryX-collab** [suidouble/suidouble8192#3]
Hello, I often encounter the error RPCError when testing, can you please tell me where to change the RPC, I've been searching for a day but I can't find a way to do it, I can pay you for it, looking forward to your reply!

**Comment by jeka-kiselyov** [comment]
@ariel841005 I am afraid suidouble library is not ready for custom rpc. You can check rpc provider initialization in SuiMaster's constructor and try to change it for your needs
